<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,0,'56eR5bm754Ot54K5');
$cfg_Cs[2]=array(0,1,0,'6ISR5rSe5YmN5rK/');
$cfg_Cs[3]=array(0,1,0,'5pWw56CB6bKc6LSn');
$cfg_Cs[4]=array(0,1,0,'56eR5oqA55m+56eR');
$cfg_Cs[5]=array(0,1,0,'5oql5bm/5Zu+5Lmm');
$cfg_Cs[6]=array(0,1,0,'56eR5bm75b2x5Ymn');
$cfg_Cs[7]=array(0,1,0,'55S156ue5ri45oiP');
$cfg_Cs[8]=array(0,1,0,'6ZOA56S+576k');
?>